import { Router } from "express";
import { randomUUID } from "node:crypto";
import { authMiddleware,adminMiddleware,requireAdminPermission,requireAuthorizedTenant,type AuthRequest } from "../middleware/auth";
import { MiraajExecution,MiraajIntegrationSettings,LOCAL_STATUSES } from "../miraaj/models";
import { getMiraajConfig } from "../miraaj/config";
import { miraajAiClient } from "../miraaj/client";
import { cancelExecution,createCanonicalExecution,synchronizeExecution } from "../miraaj/service";
import { createExecutionRequestSchema } from "../miraaj/contracts";
import { z } from "zod";
import { miraajRedis } from "../miraaj/redis";
import { writeDomainAudit } from "../domain/services/domainAudit";
import { JobDeadLetter,JobExecution } from "../jobs/persistence/jobModels";
import { JOB_NAMES } from "../jobs/contracts/jobTypes";
import { enqueueNamedJob } from "../jobs/enqueue";
import { MiraajWebhookInbox } from "../miraaj/models";
import { AuditLog } from "../models/AuditLog";
const miraajJobNames=[JOB_NAMES.MIRAAJ_SUBMIT,JOB_NAMES.MIRAAJ_SYNCHRONIZE,JOB_NAMES.MIRAAJ_CANCEL,JOB_NAMES.MIRAAJ_RECONCILE];
const router=Router();router.use(authMiddleware,adminMiddleware,requireAuthorizedTenant);
const tenant=(req:AuthRequest)=>String(req.authorizedTenantId);
const id=(req:AuthRequest)=>String(req.params.id??"");
async function allowAction(req:AuthRequest,bucket:string){const actor=req.admin?._id.toString()??"system";return miraajRedis.rateLimit(bucket,`${tenant(req)}:${actor}`,getMiraajConfig().adminRateLimit);}
type DeadLetterRecoveryDependencies={enqueue:typeof enqueueNamedJob;audit:typeof writeDomainAudit};
export async function recoverMiraajDeadLetter(input:{tenantId:string;jobDeadLetterId:string;actorId:string;reason:string},dependencies:DeadLetterRecoveryDependencies={enqueue:enqueueNamedJob,audit:writeDomainAudit}){
  const claimToken=randomUUID(),claimedAt=new Date();
  const dead=await JobDeadLetter.findOneAndUpdate(
    {tenantId:input.tenantId,jobDeadLetterId:input.jobDeadLetterId,jobName:{$in:miraajJobNames},recoveredAt:{$exists:false},$or:[{recoveryStatus:{$exists:false}},{recoveryStatus:{$in:["dead_letter","recovery_failed"]}}]},
    {$set:{recoveryStatus:"recovery_claimed",recoveryClaimedAt:claimedAt,recoveryClaimedBy:input.actorId,recoveryClaimToken:claimToken,recoveryReason:input.reason},$inc:{recoveryAttemptCount:1},$unset:{recoveryLastError:1}},
    {new:true}
  );
  if(!dead)return null;
  const envelope=dead.envelope as {payload?:Record<string,unknown>;correlationId?:string;causationId?:string};
  const idempotencyKey=`miraaj:dlq-recovery:${dead.jobDeadLetterId}`;
  try{
    const result=await dependencies.enqueue(dead.jobName,{tenantId:dead.tenantId,appKey:"admin",payload:envelope.payload??{},correlationId:envelope.correlationId??dead.correlationId,causationId:envelope.causationId,idempotencyKey,actorType:"admin",actorId:input.actorId});
    const finalized=await JobDeadLetter.findOneAndUpdate({_id:dead._id,recoveryClaimToken:claimToken,recoveryStatus:"recovery_claimed"},{$set:{recoveryStatus:"recovery_enqueued",recoveredAt:new Date(),recoveredBy:input.actorId,recoveryJobId:result.jobId},$unset:{recoveryLastError:1}},{new:true});
    if(!finalized)throw new Error("Dead-letter recovery claim was lost before finalization");
    await dependencies.audit({tenantId:input.tenantId,actorId:input.actorId,entity:"MiraajDeadLetter",entityId:dead.jobDeadLetterId,action:"miraaj.dlq.requeued",metadata:{actorRole:"admin",outcome:"success",jobName:dead.jobName,recoveryJobId:result.jobId,idempotencyKey,reason:input.reason}});
    return {jobDeadLetterId:dead.jobDeadLetterId,recoveryJobId:result.jobId,idempotencyKey};
  }catch(err){
    const safeError=err instanceof Error?err.message.slice(0,2000):"Recovery enqueue failed";
    await JobDeadLetter.updateOne({_id:dead._id,recoveryClaimToken:claimToken,recoveryStatus:"recovery_claimed"},{$set:{recoveryStatus:"recovery_failed",recoveryLastError:safeError}});
    await dependencies.audit({tenantId:input.tenantId,actorId:input.actorId,entity:"MiraajDeadLetter",entityId:dead.jobDeadLetterId,action:"miraaj.dlq.requeue_failed",metadata:{actorRole:"admin",outcome:"failed",jobName:dead.jobName,idempotencyKey,reason:safeError}});
    throw err;
  }
}
router.get("/status",requireAdminPermission("miraaj.read"),async(req:AuthRequest,res)=>{const cfg=getMiraajConfig();const [counts,circuitBreaker,settings,health,capabilities]=await Promise.all([MiraajExecution.aggregate([{$match:{tenantId:tenant(req)}},{$group:{_id:"$localStatus",count:{$sum:1}}}]),miraajAiClient.circuitState(),MiraajIntegrationSettings.findOne({tenantId:tenant(req)}).lean(),miraajRedis.readHealth<{status:string}>(),miraajRedis.readCapabilities<string[]>()]);const capabilityAgeSeconds=capabilities?Math.max(0,(Date.now()-Date.parse(capabilities.cachedAt))/1000):null;const tenantEnabled=settings?.enabled??true,tenantSubmitEnabled=settings?.submitEnabled??true,tenantSynchronizationEnabled=settings?.synchronizationEnabled??true;res.json({success:true,data:{globalEnabled:cfg.enabled,tenantEnabled,tenantSubmitEnabled,tenantSynchronizationEnabled,enabled:cfg.enabled&&tenantEnabled,maintenanceMode:cfg.maintenanceMode,submitEnabled:cfg.submitEnabled&&tenantSubmitEnabled,synchronizationEnabled:cfg.synchronizationEnabled&&tenantSynchronizationEnabled,enabledCapabilities:settings?.enabledCapabilities??[],apiVersion:cfg.apiVersion,health:!cfg.enabled?{status:"disabled",cached:false}:health?{status:health.value.status,cached:true,cachedAt:health.cachedAt}:{status:"unavailable",cached:false},capabilitiesCache:{cachedAt:capabilities?.cachedAt??null,ageSeconds:capabilityAgeSeconds,stale:capabilityAgeSeconds!==null&&capabilityAgeSeconds>cfg.capabilityCacheTtlSeconds},circuitBreaker,counts:Object.fromEntries(counts.map((row:{_id:string;count:number})=>[row._id,row.count]))}});});
router.get("/health",requireAdminPermission("miraaj.read"),async(req:AuthRequest,res)=>{try{const data=await miraajAiClient.health({tenantId:tenant(req),correlationId:String(req.header("x-correlation-id")??`health-${Date.now()}`)});res.json({success:true,data});}catch(err){res.status(503).json({success:false,error:err instanceof Error?err.message:"Miraaj unavailable"});}});
router.get("/capabilities",requireAdminPermission("miraaj.read"),async(req:AuthRequest,res)=>{try{const data=await miraajAiClient.capabilities({tenantId:tenant(req),correlationId:`cap-${Date.now()}`});res.json({success:true,data});}catch(err){res.status(503).json({success:false,error:err instanceof Error?err.message:"Miraaj unavailable"});}});
router.get("/executions",requireAdminPermission("miraaj.read"),async(req:AuthRequest,res)=>{const page=Math.max(1,Number(req.query.page)||1),limit=Math.min(100,Math.max(1,Number(req.query.limit)||20));const status=typeof req.query.status==="string"&&LOCAL_STATUSES.includes(req.query.status as typeof LOCAL_STATUSES[number])?req.query.status:undefined;const filter={tenantId:tenant(req),...(status?{localStatus:status}:{})};const [items,total]=await Promise.all([MiraajExecution.find(filter).select("-inputReference -resultReference").sort({createdAt:-1}).skip((page-1)*limit).limit(limit).lean(),MiraajExecution.countDocuments(filter)]);res.json({success:true,data:{items,total,page,limit}});});
router.get("/executions/:id",requireAdminPermission("miraaj.read"),async(req:AuthRequest,res)=>{const doc=await MiraajExecution.findOne({tenantId:tenant(req),executionId:id(req)}).lean();if(!doc){res.status(404).json({success:false,error:"Execution not found"});return;}res.json({success:true,data:doc});});
router.get("/metrics",requireAdminPermission("miraaj.read"),async(req:AuthRequest,res)=>{const tid=tenant(req),staleBefore=new Date(Date.now()-60_000);const [jobs,dlq,webhooks,latencies,queueLatency,stale,lastSync,recentErrors]=await Promise.all([JobExecution.aggregate([{$match:{tenantId:tid,jobName:{$in:miraajJobNames}}},{$group:{_id:{jobName:"$jobName",status:"$status"},count:{$sum:1}}}]),JobDeadLetter.countDocuments({tenantId:tid,jobName:{$in:miraajJobNames},recoveredAt:{$exists:false}}),MiraajWebhookInbox.aggregate([{$match:{tenantId:tid}},{$group:{_id:"$status",count:{$sum:1},last:{$max:"$updatedAt"}}}]),MiraajExecution.aggregate([{$match:{tenantId:tid,submittedAt:{$exists:true}}},{$group:{_id:null,averageSubmissionMs:{$avg:{$subtract:["$acknowledgedAt","$submittedAt"]}},averageExecutionMs:{$avg:{$subtract:[{$ifNull:["$completedAt","$failedAt"]},"$startedAt"]}}}}]),JobExecution.aggregate([{$match:{tenantId:tid,jobName:{$in:miraajJobNames},startedAt:{$exists:true}}},{$group:{_id:null,averageQueueWaitMs:{$avg:{$subtract:["$startedAt","$createdAt"]}}}}]),MiraajExecution.countDocuments({tenantId:tid,localStatus:{$in:["accepted","queued","running","synchronization_required"]},updatedAt:{$lt:staleBefore}}),MiraajExecution.findOne({tenantId:tid,lastSynchronizedAt:{$exists:true}}).sort({lastSynchronizedAt:-1}).select("lastSynchronizedAt executionId").lean(),MiraajExecution.find({tenantId:tid,errorCode:{$exists:true}}).select("executionId errorCode errorMessageSafe updatedAt").sort({updatedAt:-1}).limit(10).lean()]);res.json({success:true,data:{jobs:jobs.map((row:{_id:{jobName:string;status:string};count:number})=>({...row._id,count:row.count})),dlq,staleExecutions:stale,lastSynchronization:lastSync?{executionId:lastSync.executionId,at:lastSync.lastSynchronizedAt}:null,recentErrors,webhooks:webhooks.map((row:{_id:string;count:number;last:Date})=>({status:row._id,count:row.count,last:row.last})),latencies:{...(latencies[0]??{averageSubmissionMs:null,averageExecutionMs:null}),averageQueueWaitMs:queueLatency[0]?.averageQueueWaitMs??null}}});});
router.get("/executions/:id/timeline",requireAdminPermission("miraaj.read"),async(req:AuthRequest,res)=>{const doc=await MiraajExecution.findOne({tenantId:tenant(req),executionId:id(req)}).select("executionId tenantId correlationId").lean();if(!doc){res.status(404).json({success:false,error:"Execution not found"});return;}const entries=await AuditLog.find({"metadata.tenantId":tenant(req),$or:[{"metadata.entityId":id(req)},{"metadata.executionId":id(req)}]}).select("action metadata createdAt").sort({createdAt:1}).limit(250).lean();res.json({success:true,data:entries.map(entry=>({action:entry.action,at:entry.createdAt,outcome:entry.metadata?.outcome,reason:entry.metadata?.reason}))});});
router.get("/dead-letters",requireAdminPermission("miraaj.manage"),async(req:AuthRequest,res)=>{const items=await JobDeadLetter.find({tenantId:tenant(req),jobName:{$in:miraajJobNames}}).select("jobDeadLetterId jobName attempts lastError deadLetteredAt recoveredAt recoveryJobId").sort({deadLetteredAt:-1}).limit(100).lean();res.json({success:true,data:{items}});});
router.post("/dead-letters/:id/requeue",requireAdminPermission("miraaj.manage"),async(req:AuthRequest,res)=>{const rate=await allowAction(req,"admin-dlq");if(!rate.allowed){res.status(429).json({success:false,error:"Rate limit exceeded"});return;}try{const body=z.object({reason:z.string().trim().min(3).max(500).default("admin requested recovery")}).strict().parse(req.body??{});const result=await recoverMiraajDeadLetter({tenantId:tenant(req),jobDeadLetterId:id(req),actorId:req.admin?._id.toString()??"system",reason:body.reason});if(!result){res.status(404).json({success:false,error:"Eligible dead letter not found"});return;}res.status(202).json({success:true,data:{jobDeadLetterId:result.jobDeadLetterId,recoveryJobId:result.recoveryJobId}});}catch(err){res.status(err instanceof z.ZodError?422:503).json({success:false,error:err instanceof Error?err.message:"Dead-letter recovery failed"});}});
router.post("/test-connection",requireAdminPermission("miraaj.manage"),async(req:AuthRequest,res)=>{const actor=req.admin?._id.toString()??"system";const limit=await miraajRedis.rateLimit("admin-test",`${tenant(req)}:${actor}`,getMiraajConfig().adminRateLimit);if(!limit.allowed){res.status(429).json({success:false,error:"Rate limit exceeded"});return;}try{const data=await miraajAiClient.health({tenantId:tenant(req),correlationId:`test-${Date.now()}`},true);await writeDomainAudit({tenantId:tenant(req),actorId:actor,entity:"MiraajIntegration",entityId:tenant(req),action:"miraaj.connection.test",metadata:{actorRole:"admin",outcome:"success"}});res.json({success:true,data});}catch(err){await writeDomainAudit({tenantId:tenant(req),actorId:actor,entity:"MiraajIntegration",entityId:tenant(req),action:"miraaj.connection.test",metadata:{actorRole:"admin",outcome:"failed",reason:err instanceof Error?err.message:"unavailable"}});res.status(503).json({success:false,error:err instanceof Error?err.message:"Miraaj unavailable"});}});
router.post("/capabilities/refresh",requireAdminPermission("miraaj.manage"),async(req:AuthRequest,res)=>{try{const data=await miraajAiClient.capabilities({tenantId:tenant(req),correlationId:`cap-refresh-${Date.now()}`},true);res.json({success:true,data});}catch(err){res.status(503).json({success:false,error:err instanceof Error?err.message:"Miraaj unavailable"});}});
router.post("/executions",requireAdminPermission("miraaj.execute"),async(req:AuthRequest,res)=>{try{const body=z.object({idempotencyKey:z.string().min(8).max(128),request:createExecutionRequestSchema}).parse(req.body);const result=await createCanonicalExecution({tenantId:tenant(req),userId:req.admin?._id.toString(),idempotencyKey:body.idempotencyKey,correlationId:String(req.header("x-correlation-id")??body.idempotencyKey),request:body.request});res.status(result.reused?200:202).json({success:true,data:{executionId:result.execution.executionId,status:result.execution.localStatus,reused:result.reused}});}catch(err){res.status(422).json({success:false,error:err instanceof Error?err.message:"Invalid execution"});}});
router.post("/executions/:id/synchronize",requireAdminPermission("miraaj.manage"),async(req:AuthRequest,res)=>{try{const rate=await allowAction(req,"admin-sync");if(!rate.allowed){res.status(429).json({success:false,error:"Rate limit exceeded"});return;}await writeDomainAudit({tenantId:tenant(req),actorId:req.admin?._id.toString()??"system",entity:"MiraajExecution",entityId:id(req),action:"miraaj.execution.synchronization_requested",metadata:{actorRole:"admin",outcome:"requested"}});const doc=await synchronizeExecution(tenant(req),id(req));res.json({success:true,data:{executionId:doc.executionId,status:doc.localStatus}});}catch(err){res.status(409).json({success:false,error:err instanceof Error?err.message:"Synchronization failed"});}});
router.post("/executions/:id/retry",requireAdminPermission("miraaj.manage"),async(req:AuthRequest,res)=>{try{const rate=await allowAction(req,"admin-retry");if(!rate.allowed){res.status(429).json({success:false,error:"Rate limit exceeded"});return;}const body=z.object({idempotencyKey:z.string().min(8).max(128)}).parse(req.body);const prior=await MiraajExecution.findOne({tenantId:tenant(req),executionId:id(req),localStatus:{$in:["failed","timed_out","synchronization_required"]}});if(!prior){res.status(409).json({success:false,error:"Execution is not retryable"});return;}await writeDomainAudit({tenantId:tenant(req),actorId:req.admin?._id.toString()??"system",entity:"MiraajExecution",entityId:prior.executionId,action:"miraaj.execution.retry_requested",metadata:{actorRole:"admin",outcome:"requested",capability:prior.capability,correlationId:prior.correlationId}});const result=await createCanonicalExecution({tenantId:tenant(req),userId:req.admin?._id.toString(),campaignId:prior.campaignId,generationRunId:prior.generationRunId,idempotencyKey:body.idempotencyKey,correlationId:prior.correlationId,causationId:prior.executionId,request:createExecutionRequestSchema.parse(prior.inputReference)});res.status(202).json({success:true,data:{executionId:result.execution.executionId,status:result.execution.localStatus,reused:result.reused}});}catch(err){res.status(422).json({success:false,error:err instanceof Error?err.message:"Retry failed"});}});
router.post("/executions/:id/cancel",requireAdminPermission("miraaj.cancel"),async(req:AuthRequest,res)=>{try{const rate=await allowAction(req,"admin-cancel");if(!rate.allowed){res.status(429).json({success:false,error:"Rate limit exceeded"});return;}const doc=await cancelExecution(tenant(req),id(req),req.admin?._id.toString()??"system");res.status(202).json({success:true,data:{executionId:doc.executionId,status:doc.localStatus}});}catch(err){res.status(409).json({success:false,error:err instanceof Error?err.message:"Cancellation failed"});}});
router.patch("/settings",requireAdminPermission("miraaj.manage"),async(req:AuthRequest,res)=>{try{const body=z.object({enabled:z.boolean().optional(),submitEnabled:z.boolean().optional(),synchronizationEnabled:z.boolean().optional(),enabledCapabilities:z.array(z.string().min(1).max(128)).max(50).optional()}).strict().parse(req.body);const before=await MiraajIntegrationSettings.findOne({tenantId:tenant(req)}).lean();const data=await MiraajIntegrationSettings.findOneAndUpdate({tenantId:tenant(req)},{$set:{...body,updatedBy:req.admin?._id.toString()}},{upsert:true,new:true,setDefaultsOnInsert:true}).lean();const actorId=req.admin?._id.toString()??"system",base={tenantId:tenant(req),actorId,entity:"MiraajIntegrationSettings",entityId:tenant(req),metadata:{actorRole:"admin",outcome:"success"}};await writeDomainAudit({...base,action:"miraaj.settings.updated",before:before?{enabled:before.enabled,submitEnabled:before.submitEnabled,synchronizationEnabled:before.synchronizationEnabled,enabledCapabilities:before.enabledCapabilities}:null,after:{enabled:data?.enabled,submitEnabled:data?.submitEnabled,synchronizationEnabled:data?.synchronizationEnabled,enabledCapabilities:data?.enabledCapabilities}});const actions:Promise<void>[]=[];if(body.enabled!==undefined&&body.enabled!==before?.enabled)actions.push(writeDomainAudit({...base,action:body.enabled?"miraaj.integration.enabled":"miraaj.integration.disabled"}));if(body.submitEnabled!==undefined&&body.submitEnabled!==before?.submitEnabled)actions.push(writeDomainAudit({...base,action:body.submitEnabled?"miraaj.submission.enabled":"miraaj.submission.disabled"}));if(body.synchronizationEnabled!==undefined&&body.synchronizationEnabled!==before?.synchronizationEnabled)actions.push(writeDomainAudit({...base,action:body.synchronizationEnabled?"miraaj.synchronization.enabled":"miraaj.synchronization.disabled"}));if(body.enabledCapabilities){const old=new Set(before?.enabledCapabilities??[]),next=new Set(body.enabledCapabilities);for(const capability of new Set([...old,...next]))if(old.has(capability)!==next.has(capability))actions.push(writeDomainAudit({...base,action:next.has(capability)?"miraaj.capability.enabled":"miraaj.capability.disabled",metadata:{...base.metadata,capability}}));}await Promise.all(actions);res.json({success:true,data});}catch(err){res.status(422).json({success:false,error:err instanceof Error?err.message:"Invalid settings"});}});
export default router;
