"use client";
import { useCallback, useEffect, useState } from "react";
import { AdminPageShell } from "@/components/AdminPageShell";
import { adminFetch } from "@/lib/api";
import { GlassCard, PortalButton } from "@tasks-cash/ui";

interface StatusData { globalEnabled: boolean; tenantEnabled: boolean; tenantSubmitEnabled: boolean; tenantSynchronizationEnabled: boolean; enabled: boolean; maintenanceMode: boolean; submitEnabled: boolean; synchronizationEnabled: boolean; enabledCapabilities: string[]; apiVersion: string; health: { status: string; cached: boolean; cachedAt?: string }; capabilitiesCache: { ageSeconds: number | null; stale: boolean }; circuitBreaker: { state: string; failures: number }; counts: Record<string, number>; }
interface Execution { executionId: string; capability: string; localStatus: string; createdAt: string; updatedAt: string; errorCode?: string; }
interface Metrics { jobs: Array<{ jobName: string; status: string; count: number }>; dlq: number; staleExecutions: number; lastSynchronization: { executionId: string; at: string } | null; webhooks: Array<{ status: string; count: number; last?: string }>; latencies: { averageSubmissionMs: number | null; averageExecutionMs: number | null; averageQueueWaitMs: number | null }; recentErrors: Array<{ executionId: string; errorCode: string; errorMessageSafe?: string; updatedAt: string }>; }
interface DeadLetter { jobDeadLetterId: string; jobName: string; attempts: number; lastError?: string; deadLetteredAt: string; recoveredAt?: string; }
interface Timeline { action: string; at: string; outcome?: string; reason?: string; }

export default function MiraajIntegrationPage() {
  const [tenantId, setTenantId] = useState("public"); const [status, setStatus] = useState<StatusData | null>(null); const [metrics, setMetrics] = useState<Metrics | null>(null);
  const [items, setItems] = useState<Execution[]>([]); const [capabilities, setCapabilities] = useState<string[]>([]); const [deadLetters, setDeadLetters] = useState<DeadLetter[]>([]);
  const [timeline, setTimeline] = useState<{ executionId: string; entries: Timeline[] } | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const headers = { "x-tenant-id": tenantId };
  const load = useCallback(async () => {
    setLoading(true); setError(""); const [s, e, m, c, d] = await Promise.all([
      adminFetch<StatusData>("/api/admin/miraaj/status", { headers }), adminFetch<{ items: Execution[] }>("/api/admin/miraaj/executions?limit=25", { headers }),
      adminFetch<Metrics>("/api/admin/miraaj/metrics", { headers }), adminFetch<{ capabilities: string[] }>("/api/admin/miraaj/capabilities", { headers }), adminFetch<{ items: DeadLetter[] }>("/api/admin/miraaj/dead-letters", { headers }),
    ]);
    if (s.success && s.data) setStatus(s.data); else setError(s.error ?? "Failed to load Miraaj status"); if (e.success && e.data) setItems(e.data.items); if (m.success && m.data) setMetrics(m.data); if (c.success && c.data) setCapabilities(c.data.capabilities); if (d.success && d.data) setDeadLetters(d.data.items); setLoading(false);
  }, [tenantId]);
  useEffect(() => { void load(); }, [load]);
  async function action(path: string, message: string, body = "{}") { if (!window.confirm(message)) return; const result = await adminFetch(`/api/admin/miraaj/${path}`, { method: "POST", headers, body }); setError(result.success ? "Action accepted" : result.error ?? "Action failed"); await load(); }
  async function settings(value: Record<string, unknown>, message: string) { if (!window.confirm(message)) return; const result = await adminFetch("/api/admin/miraaj/settings", { method: "PATCH", headers, body: JSON.stringify(value) }); setError(result.success ? "Settings updated" : result.error ?? "Settings update failed"); await load(); }
  async function showTimeline(executionId: string) { const result = await adminFetch<Timeline[]>(`/api/admin/miraaj/executions/${executionId}/timeline`, { headers }); if (result.success && result.data) setTimeline({ executionId, entries: result.data }); else setError(result.error ?? "Timeline unavailable"); }
  async function toggleCapability(capability: string) { const configured = status?.enabledCapabilities ?? []; const currentlyEnabled = configured.length === 0 || configured.includes(capability); const enabledCapabilities = currentlyEnabled ? capabilities.filter((item) => item !== capability) : [...new Set([...configured, capability])]; await settings({ enabledCapabilities }, `${currentlyEnabled ? "Disable" : "Enable"} ${capability}?`); }
  const webhookCount = (state: string) => metrics?.webhooks.find((item) => item.status === state)?.count ?? 0; const duration = (value: number | null | undefined) => value == null ? "—" : `${Math.round(value)} ms`;
  const retryable = new Set(["failed", "timed_out", "synchronization_required"]); const active = new Set(["pending", "submitting", "accepted", "queued", "running", "cancelling", "synchronization_required"]);
  return <AdminPageShell title="Miraaj AI Integration" subtitle="Tasks.cash external AI execution boundary" action={<div className="flex flex-wrap gap-2"><input aria-label="Tenant ID" className="auth-input w-40" value={tenantId} onChange={(event) => setTenantId(event.target.value)} /><PortalButton size="sm" onClick={() => void load()}>Refresh</PortalButton><PortalButton size="sm" onClick={() => void action("capabilities/refresh", "Refresh capabilities from Miraaj AI?")}>Refresh capabilities</PortalButton><PortalButton size="sm" variant="gold" onClick={() => void action("test-connection", "Run a live connection test against Miraaj AI?")}>Test connection</PortalButton></div>} stats={status ? [{ label: "Enabled", value: status.enabled ? "Yes" : "No", icon: "🔌" }, { label: "Circuit", value: status.circuitBreaker.state, icon: "⚡" }, { label: "Running", value: status.counts.running ?? 0, icon: "▶" }, { label: "DLQ", value: metrics?.dlq ?? 0, icon: "⚠" }] : undefined}>
    {loading && <p className="mb-4 text-purple-200">Loading diagnostics…</p>}{error && <p className="mb-4 text-amber-300">{error}</p>}
    <GlassCard className="mb-4 p-5"><div className="grid gap-2 text-sm md:grid-cols-4"><p>Global: {status?.globalEnabled ? "Enabled" : "Disabled"}</p><p>Tenant: {status?.enabled ? "Enabled" : "Disabled"}</p><p>Health: {status?.health.status ?? "—"}{status?.health.cached ? " (cached)" : ""}</p><p>API: {status?.apiVersion ?? "—"}</p><p>Maintenance: {status?.maintenanceMode ? "On" : "Off"}</p><p>Submission: {status?.submitEnabled ? "Enabled" : "Disabled"}</p><p>Synchronization: {status?.synchronizationEnabled ? "Enabled" : "Disabled"}</p><p>Capability cache: {status?.capabilitiesCache.ageSeconds == null ? "—" : `${Math.round(status.capabilitiesCache.ageSeconds)}s${status.capabilitiesCache.stale ? " stale" : ""}`}</p><p>Circuit failures: {status?.circuitBreaker.failures ?? 0}</p><p>Stale executions: {metrics?.staleExecutions ?? 0}</p><p>Webhook accepted: {webhookCount("processed")}</p><p>Webhook rejected: {webhookCount("rejected")}</p><p>Queue wait: {duration(metrics?.latencies.averageQueueWaitMs)}</p><p>Submission: {duration(metrics?.latencies.averageSubmissionMs)}</p><p>Execution: {duration(metrics?.latencies.averageExecutionMs)}</p><p>Last sync: {metrics?.lastSynchronization ? new Date(metrics.lastSynchronization.at).toLocaleString() : "—"}</p></div><div className="mt-4 flex flex-wrap gap-2"><PortalButton size="sm" onClick={() => void settings({ enabled: !status?.enabled }, `${status?.enabled ? "Disable" : "Enable"} this tenant integration?`)}>{status?.enabled ? "Disable integration" : "Enable integration"}</PortalButton><PortalButton size="sm" onClick={() => void settings({ submitEnabled: !status?.submitEnabled }, "Change submission availability?")}>Toggle submission</PortalButton><PortalButton size="sm" onClick={() => void settings({ synchronizationEnabled: !status?.synchronizationEnabled }, "Change synchronization availability?")}>Toggle synchronization</PortalButton></div></GlassCard>
    <GlassCard className="mb-4 p-5"><h2 className="mb-3 text-lg">Capabilities</h2><div className="flex flex-wrap gap-2">{capabilities.map((capability) => { const enabled = status?.enabledCapabilities.length === 0 || status?.enabledCapabilities.includes(capability); return <button key={capability} className={`rounded px-3 py-2 text-xs ${enabled ? "bg-emerald-700" : "bg-slate-700"}`} onClick={() => void toggleCapability(capability)}>{capability}: {enabled ? "on" : "off"}</button>; })}{capabilities.length === 0 && <p>No cached capabilities.</p>}</div></GlassCard>
    <GlassCard className="mb-4 p-5"><h2 className="mb-3 text-lg">Queue jobs</h2><div className="grid gap-2 text-xs md:grid-cols-3">{metrics?.jobs.map((job) => <p key={`${job.jobName}:${job.status}`}>{job.jobName} · {job.status}: {job.count}</p>)}{metrics?.jobs.length === 0 && <p>No Miraaj jobs recorded.</p>}</div></GlassCard>
    <GlassCard className="mb-4 p-5"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-purple-300"><th className="p-2">Execution</th><th>Capability</th><th>Status</th><th>Updated</th><th>Error</th><th>Actions</th></tr></thead><tbody>{items.map((item) => <tr key={item.executionId} className="border-t border-purple-500/20"><td className="p-2 font-mono text-xs">{item.executionId}</td><td>{item.capability}</td><td>{item.localStatus}</td><td>{new Date(item.updatedAt).toLocaleString()}</td><td>{item.errorCode ?? "—"}</td><td className="flex flex-wrap gap-2 py-2"><button className="text-purple-300 underline" onClick={() => void showTimeline(item.executionId)}>Timeline</button>{active.has(item.localStatus) && <button className="text-blue-300 underline" onClick={() => void action(`executions/${item.executionId}/synchronize`, "Synchronize this execution now?")}>Sync</button>}{retryable.has(item.localStatus) && <button className="text-amber-300 underline" onClick={() => void action(`executions/${item.executionId}/retry`, "Create a new retry execution?", JSON.stringify({ idempotencyKey: `retry-${item.executionId}-${Date.now()}` }))}>Retry</button>}{active.has(item.localStatus) && <button className="text-red-300 underline" onClick={() => void action(`executions/${item.executionId}/cancel`, "Cancel this active execution?")}>Cancel</button>}</td></tr>)}</tbody></table>{!loading && items.length === 0 && <p className="p-4 text-center text-purple-200">No executions for this tenant.</p>}</div></GlassCard>
    <GlassCard className="mb-4 p-5"><h2 className="mb-3 text-lg">Dead letters</h2>{deadLetters.map((dead) => <div key={dead.jobDeadLetterId} className="mb-2 flex items-center justify-between border-b border-purple-500/20 pb-2 text-sm"><span>{dead.jobName} · {dead.attempts} attempts · {dead.lastError ?? "unknown error"}</span>{!dead.recoveredAt && <PortalButton size="sm" onClick={() => void action(`dead-letters/${dead.jobDeadLetterId}/requeue`, "Requeue this dead-lettered job?")}>Requeue</PortalButton>}</div>)}{deadLetters.length === 0 && <p className="text-sm">No Miraaj dead letters.</p>}</GlassCard>
    {timeline && <GlassCard className="p-5"><div className="mb-3 flex justify-between"><h2 className="text-lg">Timeline: {timeline.executionId}</h2><button onClick={() => setTimeline(null)}>Close</button></div>{timeline.entries.map((entry, index) => <p key={`${entry.at}:${index}`} className="border-b border-purple-500/20 py-2 text-sm">{new Date(entry.at).toLocaleString()} · {entry.action} · {entry.outcome ?? "—"}{entry.reason ? ` · ${entry.reason}` : ""}</p>)}{timeline.entries.length === 0 && <p>No timeline records.</p>}</GlassCard>}
  </AdminPageShell>;
}
