export const DEV_MOCK_REWARDS = [
  {
    _id: "mem_rw_daily",
    name: "Daily Login Streak",
    description: "Claim your daily login bonus",
    type: "coins",
    rarity: "common",
    value: 50,
    requiredLevel: 1,
    isActive: true,
    amountLabel: "50 coins",
    unlocked: true,
    owned: false,
    status: "pending" as const,
  },
  {
    _id: "mem_rw_weekly",
    name: "Weekly Challenge",
    description: "Weekly challenge completion bonus",
    type: "xp",
    rarity: "rare",
    value: 500,
    requiredLevel: 5,
    isActive: true,
    amountLabel: "500 XP",
    unlocked: false,
    owned: false,
    status: "pending" as const,
  },
  {
    _id: "mem_rw_referral",
    name: "Referral Bonus",
    description: "Bonus from successful referral",
    type: "coins",
    rarity: "epic",
    value: 100,
    requiredLevel: 1,
    isActive: true,
    amountLabel: "100 coins",
    unlocked: true,
    owned: true,
    status: "claimed" as const,
  },
  {
    _id: "mem_rw_treasure",
    name: "Treasure Chest",
    description: "Open a random loot chest",
    type: "badge",
    rarity: "legendary",
    value: 1,
    requiredLevel: 10,
    requiredCoins: 250,
    isActive: true,
    amountLabel: "Random loot",
    unlocked: true,
    owned: false,
    status: "available" as const,
  },
];
