import type { ContentAppKey } from "@tasks-cash/types";

export const CMS_APPS: { key: ContentAppKey; label: string; icon: string }[] = [
  { key: "main", label: "Main App", icon: "🌐" },
  { key: "challenge", label: "Challenge App", icon: "⚔️" },
  { key: "admin", label: "Admin App", icon: "🛡️" },
];

/** Keep in sync with services/api/src/data/contentPagesRegistry.ts */
export const CMS_PAGES: Record<ContentAppKey, { key: string; label: string }[]> = {
  main: [
    { key: "global", label: "Global / Shared" },
    { key: "home", label: "Home" },
    { key: "dashboard", label: "Dashboard" },
    { key: "login", label: "Login" },
    { key: "register", label: "Register" },
    { key: "forgot-password", label: "Forgot Password" },
    { key: "reset-password", label: "Reset Password" },
    { key: "verify-email", label: "Verify Email" },
    { key: "profile", label: "Profile" },
    { key: "settings", label: "Settings" },
    { key: "wallet", label: "Wallet" },
    { key: "notifications", label: "Notifications" },
    { key: "referrals", label: "Referrals" },
    { key: "missions", label: "Missions" },
    { key: "mystery-missions", label: "Mystery Missions" },
    { key: "worlds", label: "Worlds" },
    { key: "treasure", label: "Treasure" },
    { key: "marketplace", label: "Marketplace" },
    { key: "community", label: "Community" },
    { key: "about", label: "About" },
    { key: "faq", label: "FAQ" },
    { key: "help", label: "Help Center" },
    { key: "contact", label: "Contact" },
    { key: "leaderboards", label: "Leaderboards" },
    { key: "rewards", label: "Rewards" },
    { key: "challenges", label: "Challenges" },
    { key: "blog", label: "Blog" },
    { key: "privacy", label: "Privacy" },
    { key: "terms", label: "Terms" },
    { key: "cookies", label: "Cookies" },
    { key: "refund", label: "Refund" },
    { key: "not-found", label: "404 Not Found" },
    { key: "dashboard-missions", label: "Dashboard Missions" },
    { key: "dashboard-rewards", label: "Dashboard Rewards" },
    { key: "dashboard-withdrawals", label: "Withdrawals" },
    { key: "dashboard-support", label: "Support" },
    { key: "dashboard-security", label: "Security" },
    { key: "dashboard-level", label: "Level" },
    { key: "dashboard-leaderboard", label: "Rank" },
  ],
  challenge: [
    { key: "global", label: "Global / Shared" },
    { key: "home", label: "Home / Arena" },
    { key: "video-hunter", label: "Video Hunter" },
    { key: "referral-arena", label: "Referral Arena" },
    { key: "identity-challenge", label: "Identity Challenge" },
    { key: "special-missions", label: "Special Missions" },
    { key: "special-mission-detail", label: "Mission Details" },
    { key: "raid-arena", label: "Raid Arena" },
    { key: "duel-arena", label: "Duel Arena" },
    { key: "mystery-vault", label: "Mystery Vault" },
    { key: "leaderboards", label: "Leaderboards" },
    { key: "rewards", label: "Rewards" },
    { key: "explorer-dna", label: "Explorer DNA" },
    { key: "nav", label: "Navigation" },
  ],
  admin: [
    { key: "global", label: "Global / Shared" },
    { key: "login", label: "Login" },
    { key: "dashboard", label: "Dashboard" },
    { key: "content", label: "Content CMS" },
    { key: "settings", label: "Settings" },
    { key: "users", label: "Users" },
    { key: "missions", label: "Missions" },
    { key: "rewards", label: "Rewards" },
    { key: "referrals", label: "Referrals" },
    { key: "video-submissions", label: "Video Submissions" },
    { key: "explorer-dna", label: "Explorer DNA" },
    { key: "mystery-missions", label: "Mystery Missions" },
    { key: "dna-questions", label: "DNA Questions" },
    { key: "notifications", label: "Notifications" },
    { key: "roles", label: "Roles" },
    { key: "permissions", label: "Permissions" },
    { key: "audit-logs", label: "Audit Logs" },
    { key: "support", label: "Support" },
    { key: "withdrawals", label: "Withdrawals" },
    { key: "employees", label: "Employees" },
    { key: "levels", label: "Levels" },
    { key: "challenges", label: "Challenges" },
    { key: "treasures", label: "Treasures" },
    { key: "leaderboards", label: "Leaderboards" },
    { key: "counters", label: "Counters" },
  ],
};

export const CMS_SECTION_ORDER = [
  "hero",
  "stats",
  "cards",
  "forms",
  "table",
  "buttons",
  "messages",
  "empty_states",
  "errors",
  "nav",
  "navigation",
  "sidebar",
  "footer",
  "validation",
  "accessibility",
  "main",
] as const;

export const CMS_SECTION_LABELS: Record<string, string> = {
  hero: "Hero",
  stats: "Stats",
  cards: "Cards",
  forms: "Forms",
  table: "Table",
  buttons: "Buttons",
  messages: "Messages",
  empty_states: "Empty States",
  errors: "Errors",
  nav: "Navigation",
  navigation: "Navigation",
  sidebar: "Sidebar",
  footer: "Footer",
  validation: "Validation",
  accessibility: "Accessibility",
  main: "General",
};

export const CMS_CONTENT_TYPES = [
  "title",
  "subtitle",
  "description",
  "button",
  "label",
  "placeholder",
  "empty_state",
  "error_message",
  "success_message",
  "badge",
  "nav",
  "notice",
] as const;
