import type { IMysteryMissionView } from "@tasks-cash/types";

/** Standalone Mystery Mode — 5 curated secret missions (mock) */
export const MYSTERY_MODE_MISSIONS: IMysteryMissionView[] = [
  {
    _id: "mystery-first-trial",
    title: "FIRST TRIAL: PROVE YOUR REACH",
    description: "Prove your reach across the portal network. Submit verified video performance and complete your explorer profile.",
    difficulty: "hard",
    category: "hidden",
    missionType: "video_submission",
    unlockCondition: "none",
    unlockLabel: "Submit a video with 10K+ views + complete personal information",
    rewards: [{ type: "xp", amount: 0, label: "XP + coins + commission after approval" }],
    xpReward: 1000,
    coinReward: 500,
    coinType: "gold",
    isHidden: false,
    isFeatured: true,
    isActive: true,
    currentCompletions: 0,
    playerState: "unlocked",
    isRevealed: true,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-01T00:00:00.000Z",
  },
  {
    _id: "mystery-shadow",
    title: "SHADOW MISSION",
    description: "A mission that only reveals itself to explorers who have ascended through the void.",
    difficulty: "medium",
    category: "hidden",
    missionType: "manual_review",
    unlockCondition: "level_5",
    unlockLabel: "Reach Level 5",
    rewards: [{ type: "xp", amount: 750 }, { type: "silver_coins", amount: 200 }],
    xpReward: 750,
    coinReward: 200,
    coinType: "silver",
    isHidden: true,
    isFeatured: false,
    isActive: true,
    currentCompletions: 0,
    playerState: "locked",
    isRevealed: true,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-01T00:00:00.000Z",
  },
  {
    _id: "mystery-referral-gate",
    title: "REFERRAL GATE",
    description: "Open the referral gate by bringing allies through your portal link.",
    difficulty: "medium",
    category: "referral",
    missionType: "invite_friends",
    unlockCondition: "invite_3_friends",
    unlockLabel: "Invite 3 friends",
    rewards: [{ type: "xp", amount: 500 }, { type: "gold_coins", amount: 150 }],
    xpReward: 500,
    coinReward: 150,
    coinType: "gold",
    isHidden: true,
    isFeatured: false,
    isActive: true,
    currentCompletions: 0,
    playerState: "locked",
    isRevealed: true,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-01T00:00:00.000Z",
  },
  {
    _id: "mystery-daily",
    title: "DAILY MYSTERY",
    description: "Maintain your presence in the void for seven consecutive days to unlock this daily mystery.",
    difficulty: "hard",
    category: "daily",
    missionType: "daily_login",
    unlockCondition: "login_7_days",
    unlockLabel: "7-day login streak",
    rewards: [{ type: "mystery_box", amount: 1 }, { type: "xp", amount: 400 }],
    xpReward: 400,
    coinReward: 0,
    isHidden: true,
    isFeatured: false,
    isActive: true,
    currentCompletions: 0,
    playerState: "locked",
    isRevealed: true,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-01T00:00:00.000Z",
  },
  {
    _id: "mystery-legendary",
    title: "LEGENDARY TRIAL",
    description: "The ultimate trial reserved for explorers who have mastered the portal dimensions.",
    difficulty: "legendary",
    category: "legendary",
    missionType: "manual_review",
    unlockCondition: "level_10",
    unlockLabel: "Reach Level 10",
    rewards: [
      { type: "legend_tokens", amount: 10 },
      { type: "treasure_chest", amount: 1 },
      { type: "xp", amount: 2500 },
    ],
    xpReward: 2500,
    coinReward: 1000,
    coinType: "gold",
    isHidden: true,
    isFeatured: true,
    isActive: true,
    currentCompletions: 0,
    playerState: "locked",
    isRevealed: true,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-01T00:00:00.000Z",
  },
];
