import type { IMysteryMissionView, MysteryMissionCategory } from "@tasks-cash/types";

/** Seed mystery missions for the secret archive vault */
export const MYSTERY_MISSIONS_DATA: IMysteryMissionView[] = [
  {
    _id: "mm-001",
    title: "Portal Dawn Ritual",
    description: "Complete your daily portal scan before the void resets at midnight.",
    difficulty: "easy",
    category: "daily",
    missionType: "daily_login",
    unlockCondition: "none",
    rewards: [{ type: "xp", amount: 100 }, { type: "bronze_coins", amount: 25 }],
    xpReward: 100,
    coinReward: 25,
    coinType: "bronze",
    isHidden: false,
    isFeatured: true,
    isActive: true,
    currentCompletions: 8420,
    playerState: "unlocked",
    isRevealed: true,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-01T00:00:00.000Z",
  },
  {
    _id: "mm-002",
    title: "Void Whisper Transmission",
    description: "Share the portal broadcast on your social channel to amplify the signal.",
    difficulty: "medium",
    category: "social_media",
    missionType: "social_share",
    unlockCondition: "first_mission",
    rewards: [{ type: "silver_coins", amount: 75 }, { type: "xp", amount: 250 }],
    xpReward: 250,
    coinReward: 75,
    coinType: "silver",
    isHidden: true,
    isFeatured: false,
    isActive: true,
    currentCompletions: 1204,
    playerState: "locked",
    isRevealed: false,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-01T00:00:00.000Z",
  },
  {
    _id: "mm-003",
    title: "Neural Archive Upload",
    description: "Submit a cinematic portal walkthrough video for manual review.",
    difficulty: "hard",
    category: "video",
    missionType: "video_submission",
    unlockCondition: "level_5",
    rewards: [{ type: "gold_coins", amount: 200 }, { type: "mystery_box", amount: 1 }],
    xpReward: 500,
    coinReward: 200,
    coinType: "gold",
    isHidden: true,
    isFeatured: true,
    isActive: true,
    currentCompletions: 89,
    playerState: "locked",
    isRevealed: false,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-01T00:00:00.000Z",
  },
  {
    _id: "mm-004",
    title: "Discord Nexus Link",
    description: "Join the official Tasks.cash Discord dimension and verify membership.",
    difficulty: "easy",
    category: "community",
    missionType: "discord_join",
    unlockCondition: "none",
    rewards: [{ type: "xp", amount: 150 }, { type: "bronze_coins", amount: 50 }],
    xpReward: 150,
    coinReward: 50,
    coinType: "bronze",
    isHidden: false,
    isFeatured: false,
    isActive: true,
    currentCompletions: 5621,
    playerState: "in_progress",
    isRevealed: true,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-01T00:00:00.000Z",
  },
  {
    _id: "mm-005",
    title: "Founder's Sigil",
    description: "Unlock the legendary founder sigil reserved for the first million explorers.",
    difficulty: "legendary",
    category: "founder",
    missionType: "special_event",
    unlockCondition: "founder",
    rewards: [{ type: "founder_badge", amount: 1 }, { type: "legend_tokens", amount: 10 }, { type: "treasure_chest", amount: 1 }],
    xpReward: 2000,
    coinReward: 1000,
    coinType: "gold",
    isHidden: true,
    isFeatured: true,
    isActive: true,
    currentCompletions: 12,
    playerState: "locked",
    isRevealed: false,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-01T00:00:00.000Z",
  },
  {
    _id: "mm-006",
    title: "AI Oracle Consultation",
    description: "Complete an AI-guided strategy session and submit your mission plan.",
    difficulty: "medium",
    category: "ai",
    missionType: "manual_review",
    unlockCondition: "earn_1000_xp",
    rewards: [{ type: "diamond_gems", amount: 5 }, { type: "xp", amount: 400 }],
    xpReward: 400,
    coinReward: 0,
    isHidden: true,
    isFeatured: false,
    isActive: true,
    currentCompletions: 340,
    playerState: "locked",
    isRevealed: false,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-01T00:00:00.000Z",
  },
  {
    _id: "mm-007",
    title: "Weekly Void Hunt",
    description: "Complete 7 missions within the weekly cycle to unlock the void hunter cache.",
    difficulty: "hard",
    category: "weekly",
    missionType: "manual_review",
    unlockCondition: "login_7_days",
    rewards: [{ type: "treasure_chest", amount: 1 }, { type: "gold_coins", amount: 350 }],
    xpReward: 750,
    coinReward: 350,
    coinType: "gold",
    isHidden: true,
    isFeatured: false,
    isActive: true,
    expiresAt: "2026-06-30T00:00:00.000Z",
    currentCompletions: 2100,
    playerState: "locked",
    isRevealed: false,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-01T00:00:00.000Z",
  },
  {
    _id: "mm-008",
    title: "Referral Constellation",
    description: "Invite three allies through your portal link and witness the constellation form.",
    difficulty: "medium",
    category: "referral",
    missionType: "invite_friends",
    unlockCondition: "invite_3_friends",
    rewards: [{ type: "silver_coins", amount: 150 }, { type: "secret_badge", amount: 1 }],
    xpReward: 300,
    coinReward: 150,
    coinType: "silver",
    isHidden: true,
    isFeatured: false,
    isActive: true,
    currentCompletions: 445,
    playerState: "locked",
    isRevealed: false,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-01T00:00:00.000Z",
  },
  {
    _id: "mm-009",
    title: "Chest Triad Ritual",
    description: "Open three treasure chests to awaken the sealed triad mission.",
    difficulty: "epic",
    category: "hidden",
    missionType: "special_event",
    unlockCondition: "open_3_chests",
    rewards: [{ type: "mystery_box", amount: 2 }, { type: "diamond_gems", amount: 10 }],
    xpReward: 1000,
    coinReward: 500,
    coinType: "gold",
    isHidden: true,
    isFeatured: true,
    isActive: true,
    currentCompletions: 67,
    playerState: "locked",
    isRevealed: false,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-01T00:00:00.000Z",
  },
  {
    _id: "mm-010",
    title: "YouTube Signal Boost",
    description: "Subscribe to the official channel and sync your portal frequency.",
    difficulty: "easy",
    category: "video",
    missionType: "youtube_subscribe",
    unlockCondition: "none",
    rewards: [{ type: "bronze_coins", amount: 40 }, { type: "xp", amount: 80 }],
    xpReward: 80,
    coinReward: 40,
    coinType: "bronze",
    isHidden: false,
    isFeatured: false,
    isActive: true,
    currentCompletions: 3100,
    playerState: "completed",
    isRevealed: true,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-01T00:00:00.000Z",
  },
  {
    _id: "mm-011",
    title: "Monthly Eclipse Protocol",
    description: "Complete the full monthly eclipse cycle across all active worlds.",
    difficulty: "legendary",
    category: "monthly",
    missionType: "manual_review",
    unlockCondition: "level_10",
    rewards: [{ type: "legend_tokens", amount: 25 }, { type: "treasure_chest", amount: 3 }],
    xpReward: 2500,
    coinReward: 800,
    coinType: "gold",
    isHidden: true,
    isFeatured: true,
    isActive: true,
    currentCompletions: 23,
    playerState: "locked",
    isRevealed: false,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-01T00:00:00.000Z",
  },
  {
    _id: "mm-012",
    title: "Instagram Portal Seal",
    description: "Follow the official portal on Instagram to receive the dimensional seal.",
    difficulty: "easy",
    category: "social_media",
    missionType: "instagram_follow",
    unlockCondition: "first_mission",
    rewards: [{ type: "bronze_coins", amount: 30 }],
    xpReward: 60,
    coinReward: 30,
    coinType: "bronze",
    isHidden: true,
    isFeatured: false,
    isActive: true,
    currentCompletions: 1890,
    playerState: "under_review",
    isRevealed: true,
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-01T00:00:00.000Z",
  },
];

export function filterMysteryMissions(
  missions: IMysteryMissionView[],
  category: MysteryMissionCategory | "all"
): IMysteryMissionView[] {
  if (category === "all") return missions;
  return missions.filter((m) => m.category === category);
}

export function countByCategory(missions: IMysteryMissionView[]): Partial<Record<MysteryMissionCategory | "all", number>> {
  const counts: Partial<Record<MysteryMissionCategory | "all", number>> = { all: missions.length };
  for (const m of missions) {
    counts[m.category] = (counts[m.category] ?? 0) + 1;
  }
  return counts;
}

/** Demo: simulate unlocking a hidden mission for popup demo */
export function getDemoUnlockMission(missions: IMysteryMissionView[]): IMysteryMissionView | null {
  return missions.find((m) => m.isHidden && m.playerState === "locked") ?? null;
}
